# Backend Dockerfile
FROM golang:1.19-alpine

WORKDIR /app

COPY /backend/go.mod ./
COPY /backend/go.sum ./

RUN go mod download

COPY . ./

RUN go build -o /myapp ./cmd/api

EXPOSE 3000

CMD [ "/myapp" ]
